# interfaces(5) file used by ifup(8) and ifdown(8)
# Include files from /etc/network/interfaces.d:
source /etc/network/interfaces.d/*

auto lo
iface lo inet loopback

auto ETH0
#iface ETH0 inet dhcp
iface ETH0 inet static
        address 10.0.0.1/24

auto ETH1
#iface ETH1 inet dhcp
iface ETH1 inet static
	address 192.168.50.2

auto wlan0
iface wlan0 inet static
        hostapd /etc/hostapd/hostapd.conf
        address 10.10.0.1/24

auto wlan1
iface wlan1 inet dhcp
	wpa-ssid "IoT IMT Nord Europe"
	wpa-psk "72Hin@R*"
