# [program:ezw-dbus-user-session.service]
# priority=5
# user=swd_sk
# command=/opt/ezw/sbin/sce-dbus-user-session.sh start

# [program:ezw-stack.service]
# priority=10
# user=swd_sk
# command=/opt/ezw/sbin/sce-stack.sh start

[program:ezw-swd-left.service]
priority=15
startretries=99
autorestart=true
user=swd_sk
command=/opt/ezw/sbin/sce-swd-left.sh start

[program:ezw-swd-right.service]
priority=15
startretries=99
autorestart=true
user=swd_sk
command=/opt/ezw/sbin/sce-swd-right.sh start

[program:swd-starter-kit-bringup.service]
priority=20
startretries=99
autorestart=true
user=swd_sk
environment = HOME='/home/swd_sk'
command=/opt/ezw/sbin/sce-swd-starter-kit-bringup.sh start
stdout_logfile = /var/log/supervisor/%(program_name)s.log
stderr_logfile = /var/log/supervisor/%(program_name)s.log
logfile_maxbytes=10MB       ; (max main logfile bytes b4 rotation;default 50MB)
logfile_backups=1           ; (num of main logfile rotation backups;default 10)